name: Autograder
on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  grading:
    permissions: write-all
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          path: submission

      - name: Check repository criteria
        uses: webtech-network/autograder@v4
        with:
          template_preset: "web dev"
          feedback-type: "default"
